# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               EPROM
tagline:             'Robotic For Fun and Education'
description:         'EPROM (Elektro Poltek Robot Team) adalah Komunitas robotika Politeknik Negeri Ujung Pandang yang bertujuan untuk melakukan riset dan mengembangkan ilmu di bidang robotika.'
url:                 http://epromroffca.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Eprom Roffca
  url:               https://twitter.com/
  email:             roffca.eprom@gmail.com

# Custom vars
version:             1.0.0
